import React from 'react';
import '../styles/NotFound.css'
import img from './404.jpg'

export const NotFound = (props) => (
    <div className="mt-2 mb-2 ml-2 mr-2 mx-auto mt-10 justify-around" style={{ backgroundImage: `url(${img})`}}>
        <h1>Lorem ipsum dolor sit amet consectetur adipiscing elit maecenas, rhoncus suscipit netus tincidunt penatibus cum integer massa, felis sociosqu nulla vehicula ullamcorper mauris class. Vestibulum fringilla penatibus tortor vel arcu felis quisque malesuada facilisis, mattis aliquam dui aptent sollicitudin eleifend interdum feugiat gravida, rhoncus ante maecenas donec lobortis iaculis sodales platea. Egestas dis suscipit aliquet dui enim magnis sociosqu proin tristique, nullam sed tincidunt in porttitor et phasellus orci odio, iaculis rhoncus arcu accumsan turpis aenean dapibus convallis. Ridiculus augue donec ac erat suscipit venenatis tellus, elementum dui libero accumsan urna purus feugiat, nostra volutpat duis a odio aptent.

Magna fusce ac tincidunt et torquent molestie porta per scelerisque pulvinar id libero nascetur, velit varius ut nisi posuere dui tortor sociosqu suscipit odio auctor sodales. Mus class mollis pretium viverra odio mattis, imperdiet malesuada vulputate volutpat aliquam libero erat, neque scelerisque convallis etiam felis. Posuere ultrices per augue vitae vehicula class litora ullamcorper tempor, tortor facilisi dui neque at maecenas curae dapibus, habitasse vel rutrum taciti urna lacinia eu est. Nec pellentesque orci volutpat rhoncus non mus tempor, felis ante mattis montes curae quam quis dictum, lacinia nascetur imperdiet malesuada per ligula.

Dapibus mi curabitur neque pulvinar ut dictumst, hac facilisi eu nibh risus augue laoreet, vulputate hendrerit montes phasellus integer. Bibendum senectus vulputate tempus torquent erat etiam iaculis phasellus, ridiculus tempor ac venenatis interdum dignissim nostra, sed nulla rhoncus vivamus feugiat sollicitudin ante. Elementum taciti habitant hendrerit inceptos faucibus eget dictumst convallis condimentum, mattis nulla nostra et viverra sapien nunc imperdiet ullamcorper volutpat, urna praesent venenatis non sollicitudin interdum magna nisi. Mus morbi est nostra pharetra magnis facilisis etiam auctor duis, sed malesuada curabitur vitae sem quis himenaeos fermentum, ornare nisl sapien ridiculus ultricies class facilisi vulputate.

Fames class laoreet commodo aliquam dictum rhoncus semper curae imperdiet ante, platea hendrerit velit porta cursus vestibulum scelerisque netus vitae per, litora congue in convallis primis urna dictumst bibendum ultricies. Eleifend ornare integer eros lacus nisi quis tempor tristique, pellentesque praesent scelerisque vestibulum fames dictum a mattis, mus nibh tempus hac senectus etiam primis. Dui nisl integer senectus eget praesent pharetra nascetur blandit ante egestas dis, per sagittis netus magnis cum dapibus placerat volutpat purus neque, morbi potenti donec luctus lacinia rhoncus pellentesque sapien vehicula duis.

Id consequat mus maecenas vehicula accumsan semper platea class, cursus fames tincidunt nisl non dictum nisi pulvinar montes, magna lobortis habitant facilisis nulla natoque sed. Vehicula condimentum turpis habitasse facilisi massa est ullamcorper lobortis eget, pharetra sapien vitae hendrerit ligula cubilia aliquet ac magnis, primis nec aenean consequat dui sem nibh posuere.</h1>
    </div>
)
